name: Auto Merge to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge to gh-pages branch
        run: |
          git checkout gh-pages
          git merge --no-ff ${{ github.ref }}
          git push origin gh-pages
